# Generated by Django 6.0.3 on 2026-03-16 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_img', models.CharField(max_length=255, verbose_name='原始图片路径')),
                ('result_img', models.CharField(max_length=255, verbose_name='标注后图片路径')),
                ('disease_name', models.CharField(max_length=50, verbose_name='病害名称')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('detect_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检测时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '检测历史',
                'verbose_name_plural': '检测历史',
                'db_table': 'detect_record',
            },
        ),
    ]
