# Generated by Django 6.0.3 on 2026-03-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=30, verbose_name='植物名称')),
                ('disease_name', models.CharField(max_length=50, verbose_name='病害名称')),
                ('symptom', models.TextField(verbose_name='病害症状')),
                ('treatment', models.TextField(verbose_name='防治方法')),
            ],
            options={
                'verbose_name': '病害知识库',
                'verbose_name_plural': '病害知识库',
                'db_table': 'knowledge_info',
            },
        ),
    ]
